[package]
name = "amq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bloom = "0.2.0"
rand = "0.8.5"
boomphf = "0.5.9"
ahash = "0.8.3"